name: User Request
description: User Request
title: "github-user"
labels: ["user", "request"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - tts-admins
body:
  - type: input
    id: gsa-email
    attributes:
      label: GSA Email
      description: GSA Email
      placeholder: email@gsa.gov
    validations:
      required: true
  - type: input
    id: sponsor-email
    attributes:
      label: Sponsor Email
      description: Supervisor/Sponsor/COR Email
      placeholder: email@gsa.gov
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://handbook.tts.gsa.gov/about-us/code-of-conduct/)
      options:
        - label: I agree to follow this [Code of Conduct](https://handbook.tts.gsa.gov/about-us/code-of-conduct/)
          required: true
