name: Team Request
description: Github Team
title: "team-name"
labels: ["team", "request"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - "@GSA-TTS/tts-admins"
body:
  - type: dropdown
    attributes:
      label: System
      description: System/Program?
      multiple: false
      options:
        - "*.tts.gsa.gov"
        - analytics.usa.gov
        - Api.Data.gov
        - Challenge.gov
        - Data.gov
        - Federal Audit Clearinghouse FAC
        - Identity Verification API IDVA
        - Interagency Suspension and Debarment Committee ISDC
        - Made in America MiAO
        - Search.gov
        - Site Scanner
        - System of Records Notice SORN Dashboard
        - Tock
        - Touchpoints
        - TTS Pages
        - US Notify
        - USA.GOV
        - LOGIN.GOV
      default: 0
    validations:
      required: true  
  - type: textarea
    id: users-maintainers
    attributes:
      label: users-maintainers
      description: comma-separated list of github users - team maintainers
  - type: textarea
    id: users-members
    attributes:
      label: users-members
      description: comma-separated list of github users - team members      
  - type: textarea
    id: repos-admin
    attributes:
      label: repos-admin
      description: repos this team should have admin permissions to
  - type: textarea
    id: repos-maintain
    attributes:
      label: repos-maintain
      description: repos this team should have maintain permissions to
   - type: textarea
    id: repos-write
    attributes:
      label: repos-write
      description: repos this team should have write permissions to
   - type: textarea
    id: repos-read
    attributes:
      label: repos-read
      description: repos this team should have read permissions to          
  - type: checkboxes
    id: terms
    attributes:
      label: attestation
      description: The System Owner is aware of and approves of this team.
      options:
        - label: The System Owner is aware of and approves of this team.
          required: true
