name: Team Request
description: Github Team
title: "team-name"
labels: ["team", "request"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - "@GSA-TTS/tts-admins"
body:
  - type: dropdown
    attributes:
      label: System
      description: System/Program?
      multiple: false
      options:
        - "*.tts.gsa.gov"
        - analytics.usa.gov
        - Api.Data.gov
        - Challenge.gov
        - Data.gov
        - Federal Audit Clearinghouse FAC
        - Identity Verification API IDVA
        - Interagency Suspension and Debarment Committee ISDC
        - Made in America MiAO
        - Search.gov
        - Site Scanner
        - System of Records Notice SORN Dashboard
        - Tock
        - Touchpoints
        - TTS Pages
        - US Notify
        - USA.GOV
        - LOGIN.GOV
      default: 0
    validations:
      required: true  
  - type: textarea
    id: maintainers
    attributes:
      label: maintainers
      description: comma-separated list of github users
  - type: checkboxes
    id: terms
    attributes:
      label: attestation
      description: The System Owner is aware of and approves of this team.
      options:
        - label: The System Owner is aware of and approves of this team.
          required: true
