name: Team Request
description: Github Team
title: "team-name"
labels: ["team", "request"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - @tts-admins
body:
  - type: dropdown
    id: system
    attributes:
      label: GSA System
      multiple: false
      options:
        - analytics.usa.gov
        - Api.Data.gov
        - Challenge.gov
        - Data.gov
        - Federal Audit Clearinghouse (FAC)
        - Identity Verification API (IDVA)
        - Interagency Suspension and Debarment Committee (ISDC)
        - Made in America (MiAO)
        - Search.gov
        - Site Scanner
        - System of Records Notice (SORN) Dashboard
        - Tock
        - Touchpoints (TP)
        - TTS Pages
        - US Notify
        - USA.GOV
        - LOGIN.GOV
        - tts.gsa.gov
  - type: textarea
    id: maintainers
    attributes:
      label: maintainers
      description: Please list the GitHub Users that will be team maintainers
      render: CSV
  - type: checkboxes
    attributes:
      label: Concurrence
      description: I attest the System Owner for the selected GSA System selected above is aware and approves this team
      options:
      - label: I attest the System Owner for the selected GSA System selected above is aware and approves this team
        required: true    
  - type: markdown
    attributes:
    value: "Copy/Paste Issue link to Slack #admins-github"    
